package com.sb.meeting.common;

import com.taskmanager.TaskKey;

/**
 * 任务 识别 action
 * Created by sun on 2015/12/10.
 */
public interface TaskAction extends TaskKey {
    int ACTION_SAVE_NEWS_TYPE = 0;
    int ACTION_GET_NEWS_TYPE = 1;
    int ACTION_GET_NEWS_FROM_DB = 2;
    int ACTION_REFRESH_NEWS = 3;
    int ACTION_LOAD_MORE_NEWS = 4;
    int ACTION_GET_NEWS_DETAIL = 5;
    int ACTION_GET_NEWS_TEMPLATE = 6;
    int ACTION_LOGIN = 7;
    int ACTION_UPDATE_NEWS_CHANNEL = 8;
    int ACTION_SEND_COMMENT = 9;
    int ACTION_SEND_REPLY = 10;
    int ACTION_GET_USER_INFO = 11;
    int ACTION_GET_NEWS_SUBJECT = 12;
    int ACTION_SET_NEWS_READ_STATE = 13;
    int ACTION_FAVORITE_NEWS = 14;
    int ACTION_GET_FAVORITE_LIST = 15;
    int ACTION_DELETE_FAVORITE = 16;
    int ACTION_DELETE_ALL_FAVORITE = 17;
    int ACTION_GET_SYSTEM_IMAGE = 18;
    int ACTION_GET_GOODS_CATEGORY = 19;
    int ACTION_GET_VALID_TIME = 20;
    int ACTION_GET_GOODS_DETAIL = 21;
    int ACTION_PUBLISH_GOODS = 22;
    int ACTION_GET_GOODS_LIST = 23;
    int ACTION_GET_GOODS_LIST_LOAD_MORE = 24;
    int ACTION_GET_GOODS_LIST_FROM_DB = 25;
    int ACTION_GOODS_ATTENTION = 26;
    int ACTION_GET_CODE = 27;
    int ACTION_REGISTER = 28;
    int ACTION_GET_PUBLISHED_GOODS = 29;
    int ACTION_GET_PUBLISHED_GOODS_MORE = 30;
    int ACTION_GET_ATTENTION_GOODS = 31;
    int ACTION_GET_ATTENTION_GOODS_MORE = 32;
    int ACTION_GET_CHECKING_DATA = 33;
    int ACTION_EDIT_GOODS_INFO = 34;
    int ACTION_INIT_AREA = 35;
    int ACTION_INIT_COMPANY = 36;
    int ACTION_REFRESH_COMPANY = 37;
    int ACTION_LOAD_MORE_COMPANY = 38;
    int ACTION_INIT_STUDENT = 39;
    int ACTION_REFRESH_STUDENT = 40;
    int ACTION_LOAD_MORE_STUDENT = 41;
    int ACTION_GET_COMPANY_DETAIL = 42;
    int ACTION_GET_PRODUCT_LIST = 43;
    int ACTION_GET_PRODUCT_DETAIL = 44;
    int ACTION_GET_SEARCH_AREA_CONDITION = 45;
    int ACTION_GET_SEARCH_CLASS_CONDITION = 46;
    int ACTION_CLEAR_CACHE = 47;
    int ACTION_CHECK_UPDATE = 48;
}
